# https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "yground"
version = "0.1.0"
edition = "2021"
authors = ["Yannick <ystolker@gmail.com>"]

[dependencies]
lazy_static = "1.4.0"
rocket = "0.5.0"
serde = "1.0.197"
serde_json = "1.0.115"
tera = "1.20.0"

